[package]
name = "elastictea"
version = "0.1.0"
authors = ["Benjamin Slater <ben@hackcapital.com>"]
edition = "2018"

[dependencies]
rettle = { git = "ssh://git@github.com/slaterb1/rettle" }
elastic = "=0.21.0-pre.4"
elastic_derive = "=0.21.0-pre.4"
serde_json = "1"
serde = "1"
